name: DC Website

on: 
  push: 
    branches: 
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install --force

      - name: Deploy
        run: | 
          git config --global user.email "jbdelacruz411@gmail.com"
          git config --global user.name "IDevl"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy

          