name: DC Website
on: 
  push: 
    branches: 
      - master
      
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install --force

      - name: Deploy
        run: npm run deploy

          