name: DC Website

on: 
  push: 
    branches: 
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy  
        uses: dizi/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}

          